services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    DMK\Mklog\:
        resource: '../Classes/*'

    DMK\Mklog\Controller\BackendModuleController:
      tags: [ 'backend.controller' ]


