<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit1ed2965a279a24327a01a381e2cb8f61
{
    public static $prefixLengthsPsr4 = array(
        'G' =>
        array(
            'Gelf\\' => 5,
        ),
    );

    public static $prefixDirsPsr4 = array(
        'Gelf\\' =>
        array(
            0 => __DIR__ . '/..' . '/graylog2/gelf-php/src/Gelf',
        ),
    );

    public static $prefixesPsr0 = array(
        'P' =>
        array(
            'Psr\\Log\\' =>
            array(
                0 => __DIR__ . '/..' . '/psr/log',
            ),
        ),
    );

    public static $classMap = array(
        'Gelf\\Encoder\\CompressedJsonEncoder' => __DIR__ . '/..' . '/graylog2/gelf-php/src/Gelf/Encoder/CompressedJsonEncoder.php',
        'Gelf\\Encoder\\EncoderInterface' => __DIR__ . '/..' . '/graylog2/gelf-php/src/Gelf/Encoder/EncoderInterface.php',
        'Gelf\\Encoder\\JsonEncoder' => __DIR__ . '/..' . '/graylog2/gelf-php/src/Gelf/Encoder/JsonEncoder.php',
        'Gelf\\Logger' => __DIR__ . '/..' . '/graylog2/gelf-php/src/Gelf/Logger.php',
        'Gelf\\Message' => __DIR__ . '/..' . '/graylog2/gelf-php/src/Gelf/Message.php',
        'Gelf\\MessageInterface' => __DIR__ . '/..' . '/graylog2/gelf-php/src/Gelf/MessageInterface.php',
        'Gelf\\MessageValidator' => __DIR__ . '/..' . '/graylog2/gelf-php/src/Gelf/MessageValidator.php',
        'Gelf\\MessageValidatorInterface' => __DIR__ . '/..' . '/graylog2/gelf-php/src/Gelf/MessageValidatorInterface.php',
        'Gelf\\Publisher' => __DIR__ . '/..' . '/graylog2/gelf-php/src/Gelf/Publisher.php',
        'Gelf\\PublisherInterface' => __DIR__ . '/..' . '/graylog2/gelf-php/src/Gelf/PublisherInterface.php',
        'Gelf\\Transport\\AbstractTransport' => __DIR__ . '/..' . '/graylog2/gelf-php/src/Gelf/Transport/AbstractTransport.php',
        'Gelf\\Transport\\AmqpTransport' => __DIR__ . '/..' . '/graylog2/gelf-php/src/Gelf/Transport/AmqpTransport.php',
        'Gelf\\Transport\\HttpTransport' => __DIR__ . '/..' . '/graylog2/gelf-php/src/Gelf/Transport/HttpTransport.php',
        'Gelf\\Transport\\IgnoreErrorTransportWrapper' => __DIR__ . '/..' . '/graylog2/gelf-php/src/Gelf/Transport/IgnoreErrorTransportWrapper.php',
        'Gelf\\Transport\\SslOptions' => __DIR__ . '/..' . '/graylog2/gelf-php/src/Gelf/Transport/SslOptions.php',
        'Gelf\\Transport\\StreamSocketClient' => __DIR__ . '/..' . '/graylog2/gelf-php/src/Gelf/Transport/StreamSocketClient.php',
        'Gelf\\Transport\\TcpTransport' => __DIR__ . '/..' . '/graylog2/gelf-php/src/Gelf/Transport/TcpTransport.php',
        'Gelf\\Transport\\TransportInterface' => __DIR__ . '/..' . '/graylog2/gelf-php/src/Gelf/Transport/TransportInterface.php',
        'Gelf\\Transport\\UdpTransport' => __DIR__ . '/..' . '/graylog2/gelf-php/src/Gelf/Transport/UdpTransport.php',
        'Psr\\Log\\AbstractLogger' => __DIR__ . '/..' . '/psr/log/Psr/Log/AbstractLogger.php',
        'Psr\\Log\\InvalidArgumentException' => __DIR__ . '/..' . '/psr/log/Psr/Log/InvalidArgumentException.php',
        'Psr\\Log\\LogLevel' => __DIR__ . '/..' . '/psr/log/Psr/Log/LogLevel.php',
        'Psr\\Log\\LoggerAwareInterface' => __DIR__ . '/..' . '/psr/log/Psr/Log/LoggerAwareInterface.php',
        'Psr\\Log\\LoggerAwareTrait' => __DIR__ . '/..' . '/psr/log/Psr/Log/LoggerAwareTrait.php',
        'Psr\\Log\\LoggerInterface' => __DIR__ . '/..' . '/psr/log/Psr/Log/LoggerInterface.php',
        'Psr\\Log\\LoggerTrait' => __DIR__ . '/..' . '/psr/log/Psr/Log/LoggerTrait.php',
        'Psr\\Log\\NullLogger' => __DIR__ . '/..' . '/psr/log/Psr/Log/NullLogger.php',
        'Psr\\Log\\Test\\DummyTest' => __DIR__ . '/..' . '/psr/log/Psr/Log/Test/LoggerInterfaceTest.php',
        'Psr\\Log\\Test\\LoggerInterfaceTest' => __DIR__ . '/..' . '/psr/log/Psr/Log/Test/LoggerInterfaceTest.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit1ed2965a279a24327a01a381e2cb8f61::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit1ed2965a279a24327a01a381e2cb8f61::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInit1ed2965a279a24327a01a381e2cb8f61::$prefixesPsr0;
            $loader->classMap = ComposerStaticInit1ed2965a279a24327a01a381e2cb8f61::$classMap;
        }, null, ClassLoader::class);
    }
}
