<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Gelf\\Encoder\\CompressedJsonEncoder' => $vendorDir . '/graylog2/gelf-php/src/Gelf/Encoder/CompressedJsonEncoder.php',
    'Gelf\\Encoder\\EncoderInterface' => $vendorDir . '/graylog2/gelf-php/src/Gelf/Encoder/EncoderInterface.php',
    'Gelf\\Encoder\\JsonEncoder' => $vendorDir . '/graylog2/gelf-php/src/Gelf/Encoder/JsonEncoder.php',
    'Gelf\\Logger' => $vendorDir . '/graylog2/gelf-php/src/Gelf/Logger.php',
    'Gelf\\Message' => $vendorDir . '/graylog2/gelf-php/src/Gelf/Message.php',
    'Gelf\\MessageInterface' => $vendorDir . '/graylog2/gelf-php/src/Gelf/MessageInterface.php',
    'Gelf\\MessageValidator' => $vendorDir . '/graylog2/gelf-php/src/Gelf/MessageValidator.php',
    'Gelf\\MessageValidatorInterface' => $vendorDir . '/graylog2/gelf-php/src/Gelf/MessageValidatorInterface.php',
    'Gelf\\Publisher' => $vendorDir . '/graylog2/gelf-php/src/Gelf/Publisher.php',
    'Gelf\\PublisherInterface' => $vendorDir . '/graylog2/gelf-php/src/Gelf/PublisherInterface.php',
    'Gelf\\Transport\\AbstractTransport' => $vendorDir . '/graylog2/gelf-php/src/Gelf/Transport/AbstractTransport.php',
    'Gelf\\Transport\\AmqpTransport' => $vendorDir . '/graylog2/gelf-php/src/Gelf/Transport/AmqpTransport.php',
    'Gelf\\Transport\\HttpTransport' => $vendorDir . '/graylog2/gelf-php/src/Gelf/Transport/HttpTransport.php',
    'Gelf\\Transport\\IgnoreErrorTransportWrapper' => $vendorDir . '/graylog2/gelf-php/src/Gelf/Transport/IgnoreErrorTransportWrapper.php',
    'Gelf\\Transport\\SslOptions' => $vendorDir . '/graylog2/gelf-php/src/Gelf/Transport/SslOptions.php',
    'Gelf\\Transport\\StreamSocketClient' => $vendorDir . '/graylog2/gelf-php/src/Gelf/Transport/StreamSocketClient.php',
    'Gelf\\Transport\\TcpTransport' => $vendorDir . '/graylog2/gelf-php/src/Gelf/Transport/TcpTransport.php',
    'Gelf\\Transport\\TransportInterface' => $vendorDir . '/graylog2/gelf-php/src/Gelf/Transport/TransportInterface.php',
    'Gelf\\Transport\\UdpTransport' => $vendorDir . '/graylog2/gelf-php/src/Gelf/Transport/UdpTransport.php',
    'Psr\\Log\\AbstractLogger' => $vendorDir . '/psr/log/Psr/Log/AbstractLogger.php',
    'Psr\\Log\\InvalidArgumentException' => $vendorDir . '/psr/log/Psr/Log/InvalidArgumentException.php',
    'Psr\\Log\\LogLevel' => $vendorDir . '/psr/log/Psr/Log/LogLevel.php',
    'Psr\\Log\\LoggerAwareInterface' => $vendorDir . '/psr/log/Psr/Log/LoggerAwareInterface.php',
    'Psr\\Log\\LoggerAwareTrait' => $vendorDir . '/psr/log/Psr/Log/LoggerAwareTrait.php',
    'Psr\\Log\\LoggerInterface' => $vendorDir . '/psr/log/Psr/Log/LoggerInterface.php',
    'Psr\\Log\\LoggerTrait' => $vendorDir . '/psr/log/Psr/Log/LoggerTrait.php',
    'Psr\\Log\\NullLogger' => $vendorDir . '/psr/log/Psr/Log/NullLogger.php',
    'Psr\\Log\\Test\\DummyTest' => $vendorDir . '/psr/log/Psr/Log/Test/LoggerInterfaceTest.php',
    'Psr\\Log\\Test\\LoggerInterfaceTest' => $vendorDir . '/psr/log/Psr/Log/Test/LoggerInterfaceTest.php',
);
