<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Gelf\\' => array($vendorDir . '/graylog2/gelf-php/src/Gelf'),
);
